# Generated by Django 5.1 on 2024-08-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_chefesetor_user_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('FUNCIONARIO', 'Funcionario'), ('CHEFE', 'ChefeSetor'), ('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('EXTERNO', 'Externo')], default='EXTERNO', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
