# Generated by Django 5.1 on 2024-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_Defesa', models.DateField(verbose_name='Data de Defesa:')),
            ],
        ),
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DEFENDIDA E APROVADA', 'Defendida e Aprovada'), ('DEFENDIDA, EM DILIGÊNCIA', 'Defendida, em diligência')], max_length=255)),
                ('palavras_Chave', models.CharField(blank=True, max_length=75)),
                ('temas', models.CharField(blank=True, max_length=75)),
                ('data_de_Publicacao', models.DateField(verbose_name='Data de Publicação:')),
                ('quantidade_Paginas', models.PositiveIntegerField()),
                ('arquivo_PDF', models.FileField(upload_to='monografias/')),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('is_draft', models.BooleanField(default=False)),
            ],
            options={
                'permissions': [('approve_upload', 'pode aprovar ou não o upload de um arquivo PDF')],
            },
        ),
    ]
