# Generated by Django 5.1 on 2024-08-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_defesa', models.DateField(verbose_name='Data de Defesa da Monografia')),
            ],
        ),
        migrations.CreateModel(
            name='Monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DEFENDIDA, APROVADA', 'Defendida, Aprovada'), ('DEFENDIDA, EM DILIGÊNCIA', 'Defendida, em Diligência')], max_length=255)),
                ('resumo', models.TextField()),
                ('palavras_chave', models.CharField(blank=True, max_length=75, verbose_name='Palvavras-Chave')),
                ('temas', models.CharField(blank=True, max_length=75)),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação da Monografia')),
                ('qtd_paginas', models.PositiveIntegerField(verbose_name='Quantidade de Páginas')),
                ('arquivo_pdf', models.FileField(upload_to='monografias/', verbose_name='Arquivo em formato PDF')),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('is_rascunho', models.BooleanField(default=False, verbose_name='Rascunho')),
            ],
            options={
                'permissions': [('approve_upload', 'pode aprovar ou não o upload de um arquivo PDF')],
            },
        ),
    ]
