# Generated by Django 5.1 on 2024-08-19 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografia',
            name='banca_avaliadora',
        ),
        migrations.AddField(
            model_name='monografia',
            name='banca_avaliadora',
            field=models.ManyToManyField(limit_choices_to={'tipo_usuario': 'PROFESSOR'}, related_name='banca_avaliadores', to=settings.AUTH_USER_MODEL, verbose_name='Banca Avaliadora'),
        ),
    ]
