# Generated by Django 5.1 on 2024-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografia',
            name='checksum',
        ),
        migrations.AlterField(
            model_name='monografia',
            name='arquivo_pdf',
            field=models.FileField(upload_to='uploads/monografias/', verbose_name='Arquivo em formato PDF'),
        ),
    ]
